-- MySQL Script generated by MySQL Workbench
-- Thu May  4 11:04:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema KursDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KursDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KursDB` DEFAULT CHARACTER SET utf8 ;
USE `KursDB` ;

-- -----------------------------------------------------
-- Table `KursDB`.`DOCKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KursDB`.`DOCKS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `header` VARCHAR(64) NOT NULL,
  `category` VARCHAR(64) NOT NULL,
  `by_who` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KursDB`.`DOCKS_STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KursDB`.`DOCKS_STATUS` (
  `id_docks` INT NOT NULL,
  `executor` VARCHAR(64) NOT NULL DEFAULT 'Не назначен',
  `deadline` DATE NOT NULL,
  `responsible` VARCHAR(64) NOT NULL DEFAULT 'Не назначен',
  `complete` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id_docks`),
  CONSTRAINT `id_docks_status`
    FOREIGN KEY (`id_docks`)
    REFERENCES `KursDB`.`DOCKS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KursDB`.`PEOPLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KursDB`.`PEOPLE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(128) NOT NULL,
  `birthday` DATE NOT NULL,
  `biography` VARCHAR(512) NOT NULL,
  `photo` BLOB NULL,
  `print` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KursDB`.`AFFAIRS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KursDB`.`AFFAIRS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_docks` INT NOT NULL,
  `criminal_or_not` TINYINT NULL,
  `responsible` VARCHAR(64) NOT NULL DEFAULT 'Не назначен',
  PRIMARY KEY (`id`),
  INDEX `id_docks_idx` (`id_docks` ASC) VISIBLE,
  CONSTRAINT `id_docks_affairs`
    FOREIGN KEY (`id_docks`)
    REFERENCES `KursDB`.`DOCKS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KursDB`.`AFFAIRS_PEOPLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KursDB`.`AFFAIRS_PEOPLE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_people` INT NOT NULL,
  `id_affairs` INT NOT NULL,
  INDEX `id_affairs_idx` (`id_affairs` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_people`
    FOREIGN KEY (`id_people`)
    REFERENCES `KursDB`.`PEOPLE` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_affairs`
    FOREIGN KEY (`id_affairs`)
    REFERENCES `KursDB`.`AFFAIRS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KursDB`.`CRIMINAL_RECORDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KursDB`.`CRIMINAL_RECORDS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_people` INT NOT NULL,
  `criminal_record` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_people_criminal`
    FOREIGN KEY (`id_people`)
    REFERENCES `KursDB`.`PEOPLE` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KursDB`.`ALIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KursDB`.`ALIAS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_people` INT NOT NULL,
  `alias` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_people_alias`
    FOREIGN KEY (`id_people`)
    REFERENCES `KursDB`.`PEOPLE` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KursDB`.`DOCKS_FILES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KursDB`.`DOCKS_FILES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_docks` INT NOT NULL,
  `file` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_docks_files`
    FOREIGN KEY (`id_docks`)
    REFERENCES `KursDB`.`DOCKS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
